Q1. Write a python program to develop an ML model using KNN Classifier to predict the Species information for a given iris flower using Sepal Length, Sepal Width, Petal Length & Petal Width. Use the complete iris dataset for training. Use it to predict the species of an iris flower.

Loading the 'iris' dataset

In [2]:
import numpy as np
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()
X = iris.data 
y = iris.target

Split the dataset into training and testing sets

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

KNN classifier

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [12]:
y_pred = knn.predict(X_test)

In [13]:
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [15]:
print(y_test)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


Prediction

In [18]:
#using First values of data
sepal_length = 5.1
sepal_width = 3.5
petal_length = 1.4
petal_width = 0.2
sample_data = np.array([[sepal_length, sepal_width, petal_length, petal_width]])
prediction = knn.predict(sample_data)
result = iris.target_names[prediction][0]
print(f"Prediction is {result}")

Prediction is setosa


Q2. Print the Accuracy Score and Confusion matrix for KNN Classifier using iris data. (Split iris dataset to train and test sets.)

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix

Accuracy of the model

In [21]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 1.00


Confusion Matrix

In [22]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
